import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const Header = () => (
  <header className="bg-purple-200 py-4 px-6 shadow-md text-center">
    <h1 className="text-purple-900 font-semibold text-xl md:text-2xl">B2LP - le blog de Lyon Palme</h1>
  </header>
)

export const Footer = () => (
  <footer className="bg-purple-100 text-center py-4 mt-10 text-2xl text-purple-700">
    Développé avec ❤️ par les SIO2 - © 2026
  </footer>
)

export const metadata: Metadata = {
  title: "Le blog de Lyon Palme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-100 text-slate-800`}
      >
        {children}
      </body>
    </html>
  );
}